ALTER TABLE erp_email_history
    ADD COLUMN module VARCHAR(50) NULL DEFAULT NULL AFTER from_email,
    ADD COLUMN cc VARCHAR(500) NULL DEFAULT NULL AFTER module,
    ADD COLUMN bcc VARCHAR(500) NULL DEFAULT NULL AFTER cc,
    ADD COLUMN attachment VARCHAR(255) NULL DEFAULT NULL AFTER bcc;
