<?php

declare(strict_types=1);

namespace App\Model;

readonly class Vendor
{
    public function __construct(
        public ?int $id = null,
        public ?int $organizationId = null,
        public ?int $leadId = null,
        public ?int $vendorOwner = null,
        public string $vendorType = '',
        public ?int $vendorStatus = null,
        public ?int $vendorSource = null,
        public ?int $assignedTo = null,
        public ?string $salutation = null,
        public ?string $firstName = null,
        public ?string $lastName = null,
        public ?string $companyName = null,
        public string $displayName = '',
        public string $address = '',
        public float $openingBalance = 0.0,
        public ?int $payableAccountId = null,
        public float $creditLimit = 0.0,
        public ?string $email = null,
        public ?string $phone = null,
        public ?string $mobile = null,
        public ?int $paymentTerm = null,
        public ?int $taxTreatment = null,
        public ?string $trn = null,
        public ?string $corporateTaxNumber = null,
        public ?string $licenseNumber = null,
        public ?string $licenseExpiry = null,
        public ?int $salesPerson = null,
        public ?string $leadCategory = null,
        public ?int $csAgent = null,
        public ?int $rating = null,
        public ?int $currency = null,
        public float $exchangeRate = 1.0,
        public ?string $website = null,
        public ?string $department = null,
        public ?string $designation = null,
        public ?string $x = null,
        public ?string $facebook = null,
        public ?string $instagram = null,
        public ?string $photo = null,
        public ?string $description = null,
        public ?string $tags = null,
        public ?string $contactedDate = null,
        public bool $approved = false,
        public ?int $approvedBy = null,
        public ?string $approvedAt = null,
        public bool $publish = false,
        public bool $isActive = false,
        public ?string $createdAt = null,
        public ?string $updatedAt = null,
        public ?int $updatedBy = null,
        public int $createdBy = 0,
    ) {}

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'organization_id' => $this->organizationId,
            'lead_id' => $this->leadId,
            'vendor_owner' => $this->vendorOwner,
            'vendor_type' => $this->vendorType,
            'vendor_status' => $this->vendorStatus,
            'vendor_source' => $this->vendorSource,
            'assigned_to' => $this->assignedTo,
            'salutation' => $this->salutation,
            'first_name' => $this->firstName,
            'last_name' => $this->lastName,
            'company_name' => $this->companyName,
            'display_name' => $this->displayName,
            'address' => $this->address,
            'opening_balance' => $this->openingBalance,
            'payable_account_id' => $this->payableAccountId,
            'credit_limit' => $this->creditLimit,
            'email' => $this->email,
            'phone' => $this->phone,
            'mobile' => $this->mobile,
            'payment_term' => $this->paymentTerm,
            'tax_treatment' => $this->taxTreatment,
            'trn' => $this->trn,
            'corporate_tax_number' => $this->corporateTaxNumber,
            'license_number' => $this->licenseNumber,
            'license_expiry' => $this->licenseExpiry,
            'sales_person' => $this->salesPerson,
            'lead_category' => $this->leadCategory,
            'cs_agent' => $this->csAgent,
            'rating' => $this->rating,
            'currency' => $this->currency,
            'exchange_rate' => $this->exchangeRate,
            'website' => $this->website,
            'department' => $this->department,
            'designation' => $this->designation,
            'x' => $this->x,
            'facebook' => $this->facebook,
            'instagram' => $this->instagram,
            'photo' => $this->photo,
            'description' => $this->description,
            'tags' => $this->tags,
            'contacted_date' => $this->contactedDate,
            'approved' => $this->approved ? 1 : 0,
            'approved_by' => $this->approvedBy,
            'approved_at' => $this->approvedAt,
            'publish' => $this->publish ? 1 : 0,
            'is_active' => $this->isActive ? 1 : 0,
            'created_at' => $this->createdAt,
            'updated_at' => $this->updatedAt,
            'updated_by' => $this->updatedBy,
            'created_by' => $this->createdBy,
        ];
    }
}
